version: '3.9'

services:
  db:
    image: postgres:latest 
    environment:
      POSTGRES_DB: vacancy-api  
      POSTGRES_USER: myuser   
      POSTGRES_PASSWORD: mypassword  
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
